### ISSUE TITLE
Release 4.3 "Opération Daguet" TODO LIST

### ISSUE THREAD

**Issue by Heartbroken-Git** [Heartbroken-Git/TFP_CORE#7]
**24eBAC_Vehicles.pbo**
- [x] Retextures de l'AMV Patria BLUFOR Vanilla en VBCI Daguet
- [x] Retextures du "Fourgon Caisse" civil Vanilla en version sable (dont le PSM)
- [x] Retextures du Kamaz civil Vanilla dans le style des camion Renault en Daguet (toutes versions)
- [x] Retexture du "Hunter" Vanilla en pseudo-PVP Daguet avec les variantes non-armée, 12.7mm et 40mm
- [x] Retextures du "Tout-Terrain" Vanilla de la FIA dans le style des VLRA et P4 utilisés par les commandos en Daguet
- [x] Retextures du CRV Bobcat Vanilla de l'OTAN dans le style des EBG Daguet

**TFP_Music.pbo**
- [x] Ajout de morceaux provenant de XCOM2
- [x] Ajout du Theme for Kjell (Battlefield 4)
- [x] Ajout du morceau BONUS
- [x] Ajout du Battle Hymn of the Republic (Girls Und Panzer)
- [x] Ajout de Panzerlied (Girls Und Panzer)
- [x] Ajout du morceau Ember du Eevee EP 
- [x] Ajout du morceau Battle Mirai de Zipang 

**TFP_Patches.pbo**
- [x] Ajout des écussons France basse visibilité (sable et forêt)
- [x] Ajout de patches d'opérations françaises

**Bugfixing / Code Maintenance**
- [x] Toutes les autres issues à faire pour la R4.3 résolues

**Comment by Heartbroken-Git** [comment]
indev prête pour release. Fermeture de la Todo List
