### ISSUE TITLE
Release 5.0 "Vigipirate" TODO LIST

### ISSUE THREAD

**Issue by Heartbroken-Git** [Heartbroken-Git/TFP_CORE#8]
**24eBAC_Vehicles.pbo**
- ~~Retexture du "Buzzard" de l'AAF Vanilla style Armée de l'Air (ETO 1/8) armé et non armé~~ (mod avec des Alphajets existant)
- ~~Retexture du "Buzzard" de l'AAF Vanilla style Composante Air Belge (ETO 2/8) armé et non armé~~ (mod avec des Alphajets existant)
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des VL du SDIS 44
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des véhicules Police Nationale
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des véhicules Police Municipale
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des véhicules de l'Administration Pénitentiaire (?)
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des véhicules La Poste (blanche avec logo La poste devant et sur portière)
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des véhicules SNCF (blanche avec logo SNCF devant et sur portière)
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des véhicules Police Rurale
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des véhicules Securitas (blanche avec logo Securitas devant et sur portière)
- [x] Retexture de la "Voiture à hayon" civile Vanilla dans le style des Renault Kangoo de la Mission Vigipirate (Yup :P)
- [x] Retexture de la "Voiture à hayon de sport" civile Vanilla dans le style des véhicules des ERI de la Gendarmerie Nationale
- [x] Retexture de la "Voiture à hayon de sport" civile Vanilla dans le style des véhicules des Douanes Françaises
- [x] Retexture du "Hellcat" de l'AAF Vanilla dans un style Gendarmerie Nationale
- [x] Retexture du "Hellcat" de l'AAF Vanilla dans un style de Dragon de la Sécurité Civile
- [x] Retexture du "Hellcat" de l'AAF Vanilla dans un style Douanes Françaises
- ~~Retexture du "SUV" civil Vanilla dans le style des véhicules Gendarmerie Nationale~~ (pas possible à cause du mirroring)
- [x] Retexture du "SUV" civil Vanilla dans le style des SMUR
- ~~Retexture du "SUV" civil Vanilla dans le style des véhicules Sécuritas~~ (pas possible à cause du mirroring)
- [x] Retexture de "l'Offroad" civil Vanilla dans le style des véhicules Gendarmerie Nationale
- [x] Retexture de "l'Offroad" civil Vanilla dans le style des véhicules UIISC
- [x] Retexture de "l'Offroad" civil Vanilla dans le style des véhicules Protection Civile
- [x] Retexture de "l'Offroad" civil Vanilla dans le style de VLHR ou autre du SDIS 44
- [x] Retexture de "l'Offroad" civil Vanilla dans le style des véhicules de la CRF
- [x] Retexture de "l'Offroad" civil Vanilla dans le style des véhicules de la Police Rurale
- ~~Retexture de "l'Offroad" civil Vanilla dans le style des Land Rover Defender 110 de la Mission Vigipirate~~ (redondant avec la voiture à hayon)
- ~~Retexture de la "Vedette Armée" de l'OTAN Vanilla avec sérigraphie Gendarmerie Maritime~~ (trop puissamment armé pour être crédible)
- [x] Retexture de la "Vedette Armée" de l'OTAN Vanilla avec sérigraphie Marine Nationale (AEM)
- [x] Retexture du "Hors-Bord" civil Vanilla avec sérigraphie Douanes Françaises
- [x] Retexture du "Hors-Bord" civil Vanilla avec sérigraphie Gendarmerie Maritime
- [x] Retexture du "Hors-Bord" civil Vanilla dans le style des "Vedette de Transport d'Autorité" de la Marine Nationale
- [x] Retexture du "Orca" de la CSAT Vanilla en HELISMUR44
- [x] Retexture du "Zamak (Eau)" de l'IDAP Vanilla en CCGC du SDIS 44
- [x] Retexture du véhicule de l'AAF en VBRG
- [x] Retexture du drone BLUFOR Vanilla dans le style des Reaper employés par l'Armée de l'Air
- [x] Capacité de réparations de l'Offroad du Train, de la DGAC et de la DIR (*cf* PR #24)
- [x] Capacité de soin des PSM, véhicules CICR, MSF, Croissant Rouge, CRF, Zamak EVASAN, PC (*cf* PR #24)

**TFD_Objects.pbo**
- [x] Réalisation du drapeau de la France
- [x] Réalisation du drapeau de la Belgique
- ~~Réalisation du drapeau de la Bretagne (lol)~~ (repoussé future version)
- [x] Réalisation du drapeau de l'UE
- [x] Réalisation du drapeau de la TFP (mi FR, mi BE avec patch TFP au centre)
- [x] Réalisation du drapeau du 24eBAC
- [x] Réalisation du drapeau de la TFD
- [x] Réalisation du drapeau de l'OPEX au Koto (logo OPEX au centre + logo AA, AT, GN et MN autour)
- [x] Réalisation du drapeau de l'URSS
- [x] Réalisation d'un panneau Vigipirate (et d'une variante Vigipirate Alerte Attentat)
- [x] Réalisation des panneaux d'entrées des bases de la campagne Golden Shield
- [x] Réalisation des panneaux à l'entrée des bases militaires française (posture de protection, consignes...)
- ~~Réalisation d'une carte tactique du Koto (papier + sur tableau)~~ (campagne au Koto terminée)

**TFD_Units.pbo**
_Chaque tenue devra venir avec son unité._
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Gendarmerie Nationale
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Sécurité Privée
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Pompiers de l'Air
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Sapeurs Pompiers
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Formateur
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo CICR
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo UIISC
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Protection Civile
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Police Municipale
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo ASVP
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Police Rurale
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Douanes Françaises
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo CRF
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Administration Pénitentiaire
- [x] Retexture de la tenue de "Sheriff" civile Vanilla en Polo Police Nationale 2016
- [x] Retexture de la tenue de "Scientifique" civile Vanilla en TPB Marine Nationale
- [x] Retexture de la tenue de "Scientifique" civile Vanilla en TPB Feu Marine Nationale
- [x] Retexture de la tenue de "Scientifique" civile Vanilla en Tenue du SAMU
- [x] Retexture de la tenue de "Scientifique" civile Vanilla en Tenue de médecin CICR (Version saine et ensanglantée)
- [x] Retexture de la tenue "d'Ouvrier" civile Vanilla en Tenue de la DIR
- [x] Retexture de la tenue "d'Ouvrier" civile Vanilla en Tenue de Pistard de l'Armée de l'Air
- [x] Retexture de la tenue de "Plongeur de combat" de l'OTAN Vanilla en tenue de Plongeur Pedro (orange haute visibilité)
- [x] Retexture du "Recycleur (OTAN)" en Jaune Haute visibilité (ceci plus la tenue du dessus fait un plongeur SP)
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Gendarmerie Nationale
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Police
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Police Municipale
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Cadet (de la République)
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Protection Civile
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Police Rurale
- [x] Retexture du "Képi" et/ou de la "Casquette" en version ASVP
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Administration Pénitentiaire
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Sapeur-Pompier
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Sécurité Privée
- [x] Retexture du "Képi" et/ou de la "Casquette" en version Douanes
- [x] Retexture du "Gilet (Presse)" en pseudo Gilet S3 Centre Europe
- [x] Retexture du "Gilet (Presse)" en pseudo Gilet S3 Police Nationale
- [x] Retexture du "Gilet (Presse)" en pseudo Gilet S3 Gendarmerie Nationale
- [x] Retexture du "Gilet Tactique" en gilet Police Nationale
- [x] Retexture du "Gilet Tactique" en gilet Gendarmerie Nationale
- [x] Retexture du "Gilet Tactique" en gilet Négociateur
- [x] Retexture du "Gilet Tactique" en gilet Déminage Sécurité Civile
- [x] Retexture du "Gilet Tactique" en gilet ERIS
- [x] Retexture du "Gilet Tactique" en gilet Centre Europe
- [x] Retexture du "Gilet Tactique" en gilet haute visibilité Formateur
- [x] Retexture du "Gilet Tactique" en gilet haute visibilité Médecin
- [x] Retexture du "Gilet Tactique" en gilet haute visibilité Infirmier
- [x] Retexture du gilet de l'AAF en gilet Gendarmerie Nationale
- [x] Retexture du gilet de l'AAF en gilet Police Nationale (GIPN ?)
- [x] Retexture du gilet de l'AAF en gilet Douanes Françaises
- [x] Retexture du gilet de l'AAF lourd en gilet d'assaut lourd Gendarmerie Nationale
- [x] Retexture du gilet de l'AAF lourd en gilet d'assaut lourd Police Nationale (GIPN ?)
- [x] Retexture du gilet de l'AAF lourd en gilet d'assaut lourd Douanes Françaises
- [x] Retexture d'un casque en casque style F2 Protection Civile
- [x] Retexture d'un casque en casque style F2 Sapeurs-Pompiers (basique, chef d'agrès, chef de colonne)
- [x] Retexture de l'uniforme d'officier de l'AAF en pseudo parka Gendarmerie Nationale
- [x] Retexture de l'uniforme d'officier de l'AAF en pseudo parka Police Nationale
- [x] Retexture de l'uniforme d'officier de l'AAF en pseudo Tenue Feu Sapeurs Pompiers
- [x] Retexture d'une tenue de combat en pseudo tenue d'intervention foncée Gendarmerie Mobile
- [x] Retexture d'une tenue de combat en pseudo tenue d'intervention foncée Police Nationale
- [x] Retexture d'une tenue de combat en pseudo tenue d'intervention foncée Douanes Françaises
- [x] Retexture de la "Casquette (Sheriff)" civile Vanilla en version Formateur
- ~~Retexture du "Treillis de Survie" en Tenue de Formateur (pantalon Centre Europe, Tee shirt noir avec inscription Formateur)~~ (impossible d'éditer le tee-shirt, il est hardcodé)
- ~~Retexture du "Treillis de Survie" en Tenue de Plouf Marine Nationale (pantalon Centre Europe, Tee shirt noir avec inscription Plongeur Marine Nationale)~~ (impossible d'éditer le tee-shirt, il est hardcodé)
- ~~Retexture du "Treillis de Survie" en Tenue de de Plouf Armée de l'Air (pantalon Centre Europe, Tee shirt noir avec inscription SAR Armée de l'Air)~~ (impossible d'éditer le tee-shirt, il est hardcodé)
- [x] Retexture du "Treillis de Survie" en Tenue de de Plouf Armée de l'Air (pantalon Centre Europe, Tee shirt vanilla)
- [x] Retexture d'un casque de Karting en pseudo casque de motard Gendarmerie Nationale
- [x] Retexture du "Sac d'assaut" en sac d'intervention SP / SAMU
- ~~Faire une retexture pour avoir une tenue de facteur~~ (la tenue de chasseur n'est pas retexturable)
- [x] Retexture de la tenue de pilote d'hélicoptère Vanilla BLUFOR en tenue de pilote de la Sécurité Civile
- [x] Retexture de la tenue de pilote d'hélicoptère Vanilla BLUFOR en tenue de pilote de la Gendarmerie Nationale
- [x] Retexture du casque de pilote d'hélicoptère Vanilla BLUFOR en casque de pilote de la Sécurité Civile
- [x] Retexture du casque de pilote d'hélicoptère Vanilla BLUFOR en casque de pilote de la Gendarmerie Nationale
- [x] Retexture de la tenue de Guerilla (pullover) Vanilla en tenue de travail de l'Armée de Terre (Recrutement CIRFA)
- [x] Retexture de la tenue de Guerilla (pullover) Vanilla en tenue de travail de l'Armée de l'Air (Recrutement CIRFA)
- [x] Retexture de la tenue de Guerilla (pullover) Vanilla en tenue polaire Gendarmerie Départementale

**TFP_Music.pbo**
- ~~Retrouver tous les titres originaux des musiques de la campagne Operation GRIEVING PROMETHEUS~~ (Annulé, les joueurs ne trouve ça plus nécessaire)
- [x] Ajout du thème principal de Space : Above and Beyond
- [x] Ajout de l'instrumentale de Rains of Castamere

**TFP_Patches.pbo**
- [x] Ajout d'un patch Sapeurs Pompiers
- [x] Ajout d'un patch ASVP
- [x] Ajout d'un patch Police Nationale
- [x] Ajout d'un patch Police Municipale
- [x] Ajout de patches Gendarmerie Nationale (brigades départementales, BGA, armement, prévôtale, négociateur...)
- [x] Ajout d'un patch CRS
- [x] Ajout d'un patch Protection Civile
- [x] Ajout d'un patch CRF
- [x] Ajout de patches Sécurité Civile et/ou UIISC
- [x] Ajout de deux patches Police Rurale
- [x] Ajout d'un patch Douanes Françaises
- [x] Ajout d'un patch TFP
- [x] Ajout d'un patch La Poste
- [x] Ajout d'un patch de la flottille 35F
- [x] Ajout de patch SAR
- [x] Ajout du patch Puma SAR
- [x] ~~Ajout d'un patch DCRI~~ + patch DGSI
- [x] Ajout d'un patch ANSSI
- [x] Ajout du patch de la 2eBB
- [x] Ajout d'un patch 24eBAC ~~(variante vétéran ?)~~
- [x] Ajout d'un patch TFD
- [x] Ajout d'un patch Cadet de la République
- [x] Ajout d'un patch de l'Administration Pénitentiaire
- [x] Ajout d'un patch de l'ERIS
- [x] Ajout d'un patch de la DCPJ
- [x] Ajout d'un patch du 6eRG (intervient au Koto)
- [x] Ajout du patch du 2eREP (intervient au Koto)
- [x] Ajout du patch du Détachement de la Légion Étrangère à Mayotte (intervient au Koto)
- [x] Ajout du patch de la 9eBIMa (intervient au Koto)
- [x] Ajout du patch de la DGA
- [x] Ajout de patches du Commandement Opérationnel de Cyberdéfense 

**Général**
- [x] Créer les factions "Armée de Terre", "Marine Nationale", "Armée de l'Air" (si suffisamment d'unités pour le faire), "Gendarmerie Nationale". Les autres unités y compris de police iront en "Civils"
- [x] Placer les unités déjà créées dans les nouvelles factions
- [x] Ajouter la licence d'utilisation dans un fichier LICENCE
- [x] Ajouter des remerciements

**Bugfixing / Code Maintenance**
- [x] *Refactorer* le code (cf PR #23)
- [x] Toutes les autres issues de la 5.0 résolues
- [x] Vérifier que les nouvelles unités sont bien présentes dans Zeus
- [x] Mettre la ligne `version` des fichiers .cpp à la bonne version
